"""adiciona enum tipo usuario

Revision ID: 72a64319c4aa
Revises: 4e130884c83a
Create Date: 2025-05-22 23:16:52.568771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72a64319c4aa'
down_revision = '4e130884c83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('administrador', 'beneficiario', 'ong', 'doador', name='tipousuarioenum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('administrador', 'beneficiario', 'ong', 'doador', name='tipousuarioenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)

    # ### end Alembic commands ###
