"""add aprovado to produto

Revision ID: 76a02f3df824
Revises: af570984a19b
Create Date: 2025-05-27 23:32:01.231713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76a02f3df824'
down_revision = 'af570984a19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aprovado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.ENUM('administrador', 'beneficiario', 'ong', 'doador', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('administrador', 'beneficiario', 'ong', 'doador', collation='utf8mb4_unicode_ci'),
               nullable=False)

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('aprovado')

    # ### end Alembic commands ###
