"""cria tabela foto_produto

Revision ID: af570984a19b
Revises: 72a64319c4aa
Create Date: 2025-05-27 19:40:31.059280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af570984a19b'
down_revision = '72a64319c4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foto_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.String(length=255), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_produto')
    # ### end Alembic commands ###
