"""criação das tabelas iniciais

Revision ID: c3aa8b9908d4
Revises: 
Create Date: 2025-05-13 20:16:37.612109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aa8b9908d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('condicao', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('de_usuario_id', sa.Integer(), nullable=False),
    sa.Column('para_usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['de_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['para_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('produto')
    op.drop_table('usuario')
    op.drop_table('categoria')
    # ### end Alembic commands ###
