"""update: tirar foto da tabela produto

Revision ID: f353c95d47a6
Revises: 76a02f3df824
Create Date: 2025-05-27 23:36:57.970480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f353c95d47a6'
down_revision = '76a02f3df824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))

    # ### end Alembic commands ###
