"""update: atualizando usuario data_desativacao

Revision ID: f8472692e126
Revises: f353c95d47a6
Create Date: 2025-05-28 00:37:58.589636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8472692e126'
down_revision = 'f353c95d47a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_desativacao', sa.DateTime(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('administrador', 'beneficiario', 'moderador', 'ong', 'doador', name='tipousuarioenum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('administrador', 'beneficiario', 'moderador', 'ong', 'doador', name='tipousuarioenum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.drop_column('data_desativacao')

    # ### end Alembic commands ###
